---

- name: Docker-Minimal | Server | Installing docker server
  ansible.builtin.apt:
    name: "{{ DOCKER_HC.packages.server }}"
    state: present
  register: docker_installed

- name: Docker-Minimal | Server | Removing daemon.json
  ansible.builtin.file:
    path: '/etc/docker/daemon.json'
    state: absent
  when:
    - DOCKER.daemon_config | default(none, true) is none
    - DOCKER.proxy_url | default(none, true) is none

- name: Docker-Minimal | Server | Set proxies in daemon.json
  ansible.builtin.copy:
    dest: '/etc/docker/daemon.json'
    content: |
      {
        "proxies": {
          "http-proxy": "{{ DOCKER.proxy_url }}",
          "https-proxy": "{{ DOCKER.proxy_url }}",
          "no-proxy": "{{ DOCKER_PROXY_EXCLUDES }}"
        }
      }
    mode: 0644
  when:
    - DOCKER.daemon_config | default(none, true) is none
    - DOCKER.proxy_url | default(none, true) is not none

- name: Docker-Minimal | Server | Configuring docker service (1/2)
  ansible.builtin.file:
    path: '/etc/systemd/system/docker.service.d'
    state: directory
    owner: 'root'
    group: 'root'
    mode: 0755

- name: Docker-Minimal | Server | Configuring docker service (2/2)
  ansible.builtin.copy:
    content: |
      # ansible_managed
      # ansibleguy.infra_docker_minimal

      [Service]
      ExecStart=
      ExecStart={{ DOCKER_SVC_CMD }}
      {% if DOCKER.nftables.clean or DOCKER.nftables.reload %}
      ExecStartPost=/usr/bin/systemctl reload nftables.service
      {% endif %}

    dest: '/etc/systemd/system/docker.service.d/override.conf'
    owner: 'root'
    group: 'root'
    mode: 0755

- name: Docker-Minimal | Server | Restarting docker
  ansible.builtin.systemd:
    name: 'docker.service'
    state: restarted
    daemon_reload: yes
  when: DOCKER.tcp.enable | bool or docker_installed.changed

- name: Docker-Minimal | Server | Enabling/Starting docker service
  ansible.builtin.systemd:
    name: 'docker.service'
    state: started
    enabled: yes
